name: sklearn-custom-env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - numpy=<YOUR_VERSION_HERE>
  - scikit-learn=<YOUR_VERSION_HERE>
  - pip
  - pip:
      - joblib
      - azureml-inference-server-http
