$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
name: train_logistic_regression
display_name: Train Logistic Regression Model
type: command

code: ./src   # 👈 Folder containing train.py

command: >-
  python train.py
  --data ${{inputs.data}}
  --output ${{outputs.model_output}}

environment: azureml:AzureML-sklearn-1.3-ubuntu20.04-py310-cpu@latest

inputs:
  data:
    type: uri_file
outputs:
  model_output:
    type: uri_folder
