$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
description: Training pipeline for logistic regression

display_name: train_pipeline
experiment_name: sample-train-exp

inputs:
  input_data:
    type: uri_file
    path: azureml:sample-data@latest

outputs:
  model_output:
    type: uri_folder

jobs:
  train_job:
    type: command
    display_name: Train Logistic Regression Model
    code: ./src               # 👈 Ensure this folder exists with train.py inside
    command: >-
      python train.py
      --data ${{inputs.data}}
      --output ${{outputs.model_output}}
    environment: azureml:AzureML-sklearn-1.3-ubuntu20.04-py310-cpu@latest
    inputs:
      data: ${{parent.inputs.input_data}}
    outputs:
      model_output: ${{parent.outputs.model_output}}
    compute: azureml:cpu-cluster
