$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
description: Sklearn training pipeline.

display_name: sklearn-training-pipeline
experiment_name: sklearn-training-exp

inputs:
  training_data: 
    type: uri_file
    path: azureml://datastores/workspaceblobstore/paths/data/training-data.csv
  regularization: 0.01

outputs:
  model_output:
    mode: rw_mount

jobs:
  train_job:
    type: command
    component: azureml:train_component:1  # ✅ after you upload the component in UI
    compute: azureml:compute-cluster2
    inputs:
      training_data: ${{parent.inputs.training_data}}
      regularization: ${{parent.inputs.regularization}}
    outputs:
      model_output: ${{parent.outputs.model_output}}
