$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
description: "Training pipeline with inline component"

inputs:
  input_data:
    type: uri_file
    path: azureml://datastores/workspaceblobstore/paths/LocalUpload/f9855dded73af9327c3dbc1f9a64c774aba12508018ff3ad9e554690660ca3b1/sample_data.csv

outputs:
  model_output:
    type: uri_folder

settings:
  default_compute: azureml:cpu-cluster

jobs:
  train_job:
    component:
      name: train_component
      display_name: Train Logistic Regression Model
      type: command
      code: ./src
      command: >-
        python train.py --data ${{inputs.data}} --output ${{outputs.model_output}}
      environment: azureml:AzureML-sklearn-1.0-ubuntu20.04-py38-cpu@latest
      inputs:
        data:
          type: uri_file
      outputs:
        model_output:
          type: uri_folder
    inputs:
      data: ${{parent.inputs.input_data}}
    outputs:
      model_output: ${{parent.outputs.model_output}}
